### ISSUE TITLE
Exception with no description, looks like just a JSON response from /status page

### ISSUE THREAD

**Issue by AlexanderMatveev** [pm2-hive/pm2-php-fpm#2]
See screenshot
![keymetrics app 2015-11-20 13-49-59](https://cloud.githubusercontent.com/assets/1456669/11298114/fb38ff9a-8f8d-11e5-9ab9-af47b12646c1.png)

**Comment by kinday** [comment]
Hi, Alexander!

We throw raw nginx response when it can’t be parsed as JSON and we can’t figure out an error. One may call it a last resort.

Could you copy and paste the whole message? You may omit sensitive parts of course.

**Comment by AlexanderMatveev** [comment]
@kinday looks like it is! the message ends with:
`"start time":1448032817,"start since":143,`
But original `/status?json&full` page returns fine json.
Total length is 8010 symbols.
See screenshot. ![keymetrics app 2015-11-20 18-26-11](https://cloud.githubusercontent.com/assets/1456669/11303530/6a10c0a8-8fb4-11e5-90f3-1aa7e7fe3620.png)

**Comment by kinday** [comment]
Thanks for short but thorough answer! Now it’s more obvious where to look for the root of this issue.

**Comment by kinday** [comment]
Better late then never. Feel free to try again as soon as @alavit-d publishes `v0.0.2` to npm.

**Comment by AlexanderMatveev** [comment]
@kinday @alavit-d Thanks for this! When it will be available at npm?

**Comment by AlexanderMatveev** [comment]
Guys? =D

**Comment by alavit-d** [comment]
Published new version! Thanks for fix :+1:

**Comment by AlexanderMatveev** [comment]
@alavit-d Thanks and welcome!
